version: "3.3"

services:
  db_gitlab:
    image: mysql
    container_name: db_docker_gitlab
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  www_gitlab:
    build: php
    container_name: www_docker_gitlab
    ports:
      - "8080:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ../:/var/www
    restart: always
    networks:
      - dev

#  phpmyadmin:
#    image: phpmyadmin
#    container_name: phpmyadmin_docker_gitlab
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8080:80
#    environment:
#      PMA_HOST: db
#    networks:
#      - dev
#
#  maildev:
#    image: maildev/maildev
#    container_name: maildev_docker_gitlab
#    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
#    ports:
#      - "8081:80"
#    restart: always
#    networks:
#      - dev

networks:
  dev:

volumes:
  db-data:

